default: &default
  global:
    description: "oltp.extract.{}.{}.{}.convert.{}.file"
    default_timezone: "America/Sao_Paulo"
  
  metadata:
    hostname: ???
    port: ???
    username: ???
    password: ???
    database: ???

qa:
  <<: *default

production:

  global:
    description: "oltp.extract.{}.{}.{}.convert.{}.file"
    default_timezone: "America/Sao_Paulo"
  
  metadata:
    hostname: ???
    port: ???
    username: ???
    password: ???
    database: ???
